# Generated by Django 2.2 on 2019-04-17 21:55

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'data.json'
def load_data(apps, schema_editor):
    Shop = apps.get_model('shops', 'Shop')
    #construct the absolute path using the Path class of the pathlib library:Path(object attribute i.e file).directory/file name 
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    #open the data
    with open(str(jsonfile)) as datafile:
        #parse the JSON file into a Python object
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    #return a valid GEOSGeometry object corresponding to the spatial data in the string 
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326) #*
                    #assign to the location field and save the instance of the Shop model
                    Shop(name=name, location = location).save()
            except KeyError:
                pass    

#* f-string for formatting the argument of fromstr()
#* srid stands for Spatial Reference System Identifier. 
#* It’s a unique value to identify spatial reference systems (projection systems used for interpreting the data in the spatial database).
#* 4326 -aka WGS84- being the most popular system used with PostGIS. Refer: spatialreference.org

#added migration class to execute the above load_data function
# class Migration(migrations.Migration):

#     dependencies = [
#         ('shops', '0005_auto_20181018_2050'),
#     ]

#     operations = [
#         migrations.RunPython(load_data)
#     ]


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
